# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               DimbleData
tagline:             Welcome...to Question Time
description:         ''
url:                 http://dunkenj.github.io/DimbleData/
baseurl:             http://dunkenj.github.io/DimbleData/
paginate:            5

# About/contact
author:
  name:              Ken Duncan
  url:               https://twitter.com/dunkenj
  email:             

# Custom vars
version:             1.0.0
